### ISSUE TITLE
Cant start WSL after moving from C: to D:

### ISSUE THREAD

**Issue by MarjanCinnamon** [microsoft/WSL#9927]
### Windows Version

Microsoft Windows [Version 10.0.19044.2728]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps
```
wsl --list -v
wsl --export Ubuntu ubuntu.tar
wsl --unregister Ubuntu
mkdir D:\WSL\
wsl --import Ubuntu20.04 D:\WSL\Ubuntu20.04 C:\Users\marja\AppData\Local\Docker\wsl\data\ext4.vhdx --vhd

wsl --set-default Ubuntu20.04
wsl
```

### Expected Behavior

enter wsl shell

### Actual Behavior

```PS D:\> wsl
Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:368: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:372: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:574: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:583: Create process not expected to return
PS D:\>

**Comment by mariorecinos** [comment]
It seems like there is an issue with the mount points for your WSL distribution after you moved it from the C: drive to the D: drive.

One possible solution is to update the mount points in the /etc/fstab file of your WSL distribution. You can try the following steps:

Open your WSL distribution by running

 wsl 

in the command prompt.
Edit the /etc/fstab file by running
 sudo nano /etc/fstab.
Update the mount points for your WSL distribution to match the new location on the D: drive. For example, if your WSL distribution was originally located in /mnt/c, you may need to update it to /mnt/d or another appropriate mount point on the D: drive.
Save the changes to the /etc/fstab file and exit the editor.
Run
 sudo mount -a 
to apply the changes to the mount points.
Exit the WSL distribution by running exit.
Try starting the WSL distribution again by running wsl.
If the above steps do not work, you may need to try recreating your WSL distribution from scratch on the D: drive. This can be done by following the steps outlined in the Microsoft documentation: https://docs.microsoft.com/en-us/windows/wsl/install-win10#move-your-linux-distros-to-another-drive.

**Comment by elsaco** [comment]
@MarjanCinnamon in step nr.2 you're exporting to a tar file then why not import the tar in step nr.5?  In step nr. 3 you unregistered the Ubuntu distro and that will wipe out the `ext4.vhdx` associated with it.  Who's `vhdx` are you importing? 

The `Processing fstab with mount -a failed` is not your issue. Some of the older WSL Ubuntu images have `LABEL=cloudimg-rootfs   /        ext4   defaults        0 1` in the `/etc/fstab` causing the message to appear on the console.

**Comment by MarjanCinnamon** [comment]
hey @mariorecinos i am not able to run my wsl distribution in any way. I've already created a fresh instance, but i had important data on the previous one, is there a way i can extract those if i have the original ext4.vhdx file?

**Comment by benhillis** [comment]
In your repro looks like you exported a tar, but you're trying to import a vhd?

**Comment by mariorecinos** [comment]
> 

Yes, if you have the original ext4.vhdx file from your previous WSL distribution, you can extract your important data from it.

Here are the steps you can follow:

Create a new WSL distribution by running the command 

wsl --import <DistributionName> <InstallLocation> <ext4.vhdx>. 

Replace <DistributionName> with the name you want to give to the new distribution, <InstallLocation> with the path where you want to install the new distribution, and <ext4.vhdx> with the path to the original ext4.vhdx file.
Open the new distribution and create a mount point by running the command sudo mkdir /mnt/oldroot.
Mount the original ext4.vhdx file by running the command sudo mount -t ext4 -o loop,ro /mnt/<DistributionName>/ext4.vhdx /mnt/oldroot. Replace <DistributionName> with the name of the new distribution you created in step 1.
Navigate to the mount point by running the command cd /mnt/oldroot and you should be able to access your important data.
Copy the files or directories you need from the mount point to a safe location outside the WSL file system, such as your Windows file system.
Note that some of the files in the ext4.vhdx file may have permissions that prevent you from accessing them as a regular user. In this case, you may need to run some commands with sudo to gain the necessary permissions.

Here are some references that discuss the process of extracting data from an ext4.vhdx file in WSL:

Microsoft documentation on accessing Linux files from Windows: https://docs.microsoft.com/en-us/windows/wsl/access-files
A Medium article that provides step-by-step instructions for accessing data from a corrupted WSL distribution: https://medium.com/@gauravnelson/recovering-data-from-a-corrupted-wsl-2-instance-d58578b565ec
A Reddit thread where users discuss how to recover data from a deleted WSL distribution: https://www.reddit.com/r/bashonubuntuonwindows/comments/f0m8qa/recovering_data_from_deleted_wsl_2_instance/

I hope these references are helpful!

**Comment by tuliofaria** [comment]
Just a quick note about what worked for me. After moving to another drive, my default distro was unregistered.
So using: 
`wsl -s <Distro>` made it works.

Ref: https://github.com/microsoft/WSL/issues/5923#issuecomment-1215454084
