### ISSUE TITLE
Enabling systemd clears out apt sources.list and files under /etc/apt/sources.list.d/

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [microsoft/WSL#9934]
### Windows Version

10.0.22000.1761

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Enabling `systemd` by adding this to `/etc/wsl.conf`
```
[boot]
systemd=true
```
It triggers `apt` sources to be cleared out and `sources.list` to become `sources.list.pre-firstboot` as if it runs for the first time even though it has been configured before.

Is there a way to prevent it from changing `apt` sources when enabling `systemd`

### Expected Behavior

WSL starts without clearing out `apt` sources

### Actual Behavior

It triggers `apt` sources to be cleared out and `sources.list` to become `sources.list.pre-firstboot` as if it runs for the first time even though it has been configured before. It also clears out repositories listed in `/etc/apt/sources.list.d/`?

**Comment by Biswa96** [comment]
I have not seen this kind of issue after enabling systemd. Does this happen with Ubuntu 20.04 only? Did you check that with any other version of Ubuntu or with other Linux distributions?

**Comment by HenrikFrystykNielsen** [comment]
It was because `systemd` had these two services enabled: `apt-daily.service` and `apt-daily-upgrade.service`. After disabling them the problem went away. See also https://askubuntu.com/questions/1038923/do-i-really-need-apt-daily-service-and-apt-daily-upgrade-service

**Comment by HenrikFrystykNielsen** [comment]
well, I spoke too soon -- disabling these didn't help -- the original issue still stands

**Comment by HenrikFrystykNielsen** [comment]
It seems to be `firstboot.service` that I had to disable.
