### ISSUE TITLE
Cmake freezes completely

### ISSUE THREAD

**Issue by illegal-instruction-co** [microsoft/WSL#9939]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

22.04

### Other Software

Whenever i try to compile big c++ project with
make -j 15 ( totally 18 cores )
it freezes randomly percent like 20 or 25. i tried it with multiple projects, little ones doesnt affected but big ones always freezed the wsl.

### Repro Steps

Download big cmake project and compile it with gcc12

### Expected Behavior

Compile correctly

### Actual Behavior

Freezes

**Comment by benhillis** [comment]
Sorry, need more details. Where are you building your project out of, the ext4 partition, one of your mounted windows drives? Will need repro steps to investigate.

**Comment by illegal-instruction-co** [comment]
We can close the issue, it seems like memory issue. I had extended the memory usage by using wslconfig as 16 gb to 30 gb. After this adjustment on legacy default, it seems rarely freezing ( not solved at all)
