### ISSUE TITLE
WSL2 freezes/timeout upon launch (cannot start)

### ISSUE THREAD

**Issue by jerryc05** [microsoft/WSL#9942]
### Windows Version

Microsoft Windows [Version 10.0.22621.1485]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Can't start

### Distro Version

Ubuntu

### Other Software

(Maybe not related)
Error initially starts from using cmake & gcc to build a very large project (llvm) and then suddenly Ubuntu mounts all filesystems as read only, and most shell commands stop working (`Input/output error`). Now after I restarted my PC and try to launch WSL again, it hangs and did not respond.

### Repro Steps

Start Ubuntu WSL from the command line

### Expected Behavior

no error

### Actual Behavior

Hangs and then displays timeout error `Wsl/Service/CreateInstance/HCS_E_CONNECTION_TIMEOUT`

### Diagnostic Logs

[WslLogs-2023-04-10_16-38-42.zip](https://github.com/microsoft/WSL/files/11193899/WslLogs-2023-04-10_16-38-42.zip)
Logs attached

**Comment by benhillis** [comment]
Thanks for the logs! Looks like things are getting stuck attaching one of the VHDs. @kelsey-steele - I'm seeing a bunch of errors that look like this in dmesg:
```
[   96.100309] hv_storvsc fd1d2cbd-ce7c-535c-966b-eb5f811c95f0: tag#829 cmd 0x2a status: scsi 0x2 srb 0x4 hv 0xc0000001 
```

Do you have any idea what could be happening here? I'm not really seeing anything in the stovcp logs from the host.

**Comment by kelsey-steele** [comment]
> Thanks for the logs! Looks like things are getting stuck attaching one of the VHDs. @kelsey-steele - I'm seeing a bunch of errors that look like this in dmesg:
> 
> ```
> [   96.100309] hv_storvsc fd1d2cbd-ce7c-535c-966b-eb5f811c95f0: tag#829 cmd 0x2a status: scsi 0x2 srb 0x4 hv 0xc0000001 
> ```
> 
> Do you have any idea what could be happening here? I'm not really seeing anything in the stovcp logs from the host.

I would really need to see more. @benhillis can you direct me to where you grabbed that dmesg line from the logs or forward the rest to me? Is the "KernelVersion"="5.10.102.1" in HKLM.txt accurate for current build? This seems quite off, so I'm assuming a bit this isn't up to date.

Regarding the hv_storvsc error, cmd 0x2a shows to be a write command, which looks like it would line up with the build that was in progress. I'm wondering if a corruption occurred during the install and the switch to read-only was a result of that? 

@jerryc05, Sorry to hear this has happened and I appreciate you sending what information you could. 

With you re-installing Ubuntu, does that mean other WSL distros were left unharmed? Did you try installing llvm after the reinstall? Then finally, can you please send us the output of "wsl --version" ran in powershell? Thank you! :)

**Comment by jerryc05** [comment]
@kelsey-steele 
> does that mean other WSL distros were left unharmed
well, I only encountered this error on my Ubuntu WSL. I guess all other WSL works (but I did not check it at the time I captured this log)
> Did you try installing llvm after the reinstall
everything went just fine after reinstall. idk what triggered this bug, might be a filesystem corruption (just guessing) under super high CPU and disk load
> wsl --version

```
PS C:\WINDOWS\system32> wsl --version
WSL version: 1.2.0.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1485
```

**Comment by kelsey-steele** [comment]
@jerryc05 appreciate the information. Glad everything is working now at least! I'll poke around this a bit more and see if I can get any more information or ideas for what happened; definitely want to try preventing it from happening again or to others. Please ping me if you notice anything going awry again with your Ubuntu instance.
