### ISSUE TITLE
DNS error after I change internet connection from Wifi to LAN or vice versa (host Windows 10 - Ubuntu 22.04)

### ISSUE THREAD

**Issue by taweijm** [microsoft/WSL#9943]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04.2 LTS

### Repro Steps

My Steps are here :

1. set computer connection to Wifi 
2. install wsl from cmd/power shell using wsl --install -d ubuntu
3. after finish, run wsl2 (wsl_update_x64.msi)
4. login to ubuntu, ping google.com are fine and internet connection is good
5. while still on ubuntu, change computer connection to LAN
6. ping google give error "ping: google.com: Temporary failure in name resolution"
7. I tried every possible way (via googling) but cannot fix the problem
    a. terminate and starting ubuntu
    b. change /etc/resolv.conf and /etc/wsl.conf
    c. flush dns in windows 
    d. restart windows
    e. sudo ln -s ../run/resolvconf/resolv.conf resolv.conf
    f. add IP gateway to eth0 using sudo ip addr add
8. When I changed computer connection to Wifi, command "ping google.com" still error

### Expected Behavior

When change connection from wifi to LAN or otherwise, the WSL should maintain DNS automaticly 

### Actual Behavior

Ping or sudo apt or pip command did not work

**Comment by zcobol** [comment]
@taweijm before you switch connections, from an elevated powershell session run `get-hnsendpoint` to show the IPAdrdress assigned to the WSL instance. After switching from Wi-Fi to LAN run the command again. The enpoint info shouldn't change if using the default virtual switch setup by WSL installation. Also, run `hnsdiag.exe list all` to see if anything changes. Again, the enpoint info shouldn't change.  Did not repro on Windows 11, however you filed the bug for Windows 10.

**Comment by taweijm** [comment]
Before switch connnection and after switch connection, the end point still
the same :

VirtualNetworkName : WSL
IPAddress          : 192.168.13.236
GatewayAddress     : 192.168.0.1
DNSServerList      : 192.168.0.1

after running hnsdiag.exe list all, I get this
////////////////////////NETWORKS///////////////////////

Network : B95D0C5E-57D4-412B-B571-18A81A16E005
    Name             : WSL
    Type             : ICS
    Subnet Address   : 192.168.0.0/20
    Gateway          : 192.168.0.1

///////////////////////ENDPOINTS///////////////////////

Endpoint         : d5430601-9fec-4675-8417-73411e720449
    Name             : Ethernet
    IP Address       : 192.168.13.236

After switching to LAN, the problem exist

--- google.com ping statistics ---
12 packets transmitted, 0 received, 100% packet loss, time 11462ms
