### ISSUE TITLE
In WSL 1.2.0.0 Running MS SQL Server 2022 Image in Docker Fails - Reverting to WSL 1.1.6.0 fixes issue

### ISSUE THREAD

**Issue by bb-avi** [microsoft/WSL#9957]
### Windows Version

10.0.22621.1555

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Other Software

Docker Desktop 4.18.0
[mcr.microsoft.com/mssql/server:2022-latest](https://github.com/microsoft/WSL/issues/new?assignees=&labels=&template=Bug_Report.yaml#) on Ubuntu 20.04.5 LTS

### Repro Steps

# Launch container
docker run --detach --name mssql -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$plainTempSaPwd" --platform linux -p 1433:1433 mcr.microsoft.com/mssql/server:2022-latest

# Look at logs
docker logs mssql

# see error in logs: `ERROR: CoInitializeSecurity failure. (HRESULT 0x800706b5)`

# see that container does not keep running
docker container ls --all

### Expected Behavior

Container should keep running and not have security failure.

### Actual Behavior

Container writes `ERROR: CoInitializeSecurity failure. (HRESULT 0x800706b5)` and stops

**Comment by jackawatts** [comment]
Not the OP but I have the same issue.

I have run the script, here are the logs.

If someone could provide me with instructions how to revert to an earlier version of wsl it would be most appreciated.
[WslLogs-2023-04-13_21-49-39.zip](https://github.com/microsoft/WSL/files/11221803/WslLogs-2023-04-13_21-49-39.zip)

**Comment by benhillis** [comment]
@jackawatts - the only thing I'm seeing in that log is some information about the localhost relay failing. This was fixed in 1.2.1. I'm not seeing any evidence of the com error in our logs.

**Comment by jackawatts** [comment]
Thanks @benhillis 

Great to hear it has been addressed in 1.2.1

I'm still stuck on 1.2.0 and am unable to get this working.

How can I get access to 1.2.1?

Happy to run an update script a KB or something else.  I just can't seem to find anything in the doco, only info about changing from 2 to 1 or vice versa which I'm not looking to do.

Unfortunately I need to get this fixed.  perhaps just an update as to when the new version would be delivered would be sufficient as well.

Thanks for following up!

**Comment by jackawatts** [comment]
Despite not being the OP, this issue can likely be closed with @benhillis response being the definitive answer.

**Comment by bb-avi** [comment]
Updating wsl to 1.2.2 fixes the issue for me too!

`wsl --update --pre-release`

**Comment by baoanhng** [comment]
Upgrading to 1.2.2 does fix the issue.
