### ISSUE TITLE
When WSL is updated via the MS Store it is terminated with an error of [process exited with code 1 (0x00000001)]

### ISSUE THREAD

**Issue by bgupta** [microsoft/WSL#9958]
### Windows Version

Microsoft Windows [Version 10.0.22621.1485]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Wait for the MS store to update WSL while Terminal sessions are active.

### Expected Behavior

WSL won't terminate unless you force it to or reboot.

### Actual Behavior

It terminates when Ms store updates the package.

**Comment by enzofoucaud** [comment]
Same error code

**Comment by benhillis** [comment]
@craigloewen-msft - do we know when the store update that resolves this issue will be pushed out?

**Comment by MrMarvel** [comment]
Same there.
Starting wsl.
Closing wsl. Waiting some time
BUT There is wslservice.exe and vmmem (big)
wsl --shutdown
vmmem closed but wsl.service still there
