### ISSUE TITLE
Windows Explorer Shell Copy should respect NTFS extended attributes

### ISSUE THREAD

**Issue by fpqc** [microsoft/WSL#997]
This isn't really a feature request for the WSL team, but maybe they can forward it on to the correct team at Microsoft.  Posting here because the use case is directly motivated by WSL.

The way that Explorer implements Move (Cut & Paste) preserves extended NTFS attributes, and makes it play relatively nicely with WSL.  We also know that the commandline program `robocopy.exe` can also preserve the extended attributes.  However the Windows Explorer shell's copy/paste implementation breaks them, which seems like inconsistent behavior.  

Could MS change the copy/paste functionality in Explorer to behave more like robocopy (bonus is robocopy can also operate on paths above the old maxpath size)?

**Comment by benhillis** [comment]
Agreed, marking this as a bug so we can follow up with the appropriate teams.
