### ISSUE TITLE
Implement \\?\ Pathing - Bypass MAXPATH Limitations

### ISSUE THREAD

**Issue by AdamDanischewski** [microsoft/WSL#9988]
Problem: MAXPATH is not bypassable by way of \\\\?\ prefixing - currently the limit on path names is 256 (really less space for a filename to 247). 

Windows 10 users can change a registry setting, that workaround broke and no longer works as of Windows 11. 

[MAXPATH Limitation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)

This problem affects backups via rsnapshot and really any tool that encounters a long ntfs paths including yet not limited to icacls. Running the same with \\\\?\ allows the tools to run properly, Unfortunately there is no way I know of to bypass this. 

It would be nice if both WSL 1 and WSL 2 could be modified to allow for utilization of \\\\?\ paths. 

I for one am trapped on WSL 1 since my AMD Ryzen 7 is not compatible with enabling virtualization to the extent needed by WSL 2 (ftpm problem, fyi without the wsl 2 crippling fixes that were implemented computer is unstable would crash randomly). 

```
PS C:\>  dir \\?\d:\backups
    
Directory: \\?\d:

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/12/2023   3:12 AM                backups

```

```
:~$ wslpath '\\?\d:\backups'
/mnt/d/backups

```

Specifically it would be nice if: `//?/mnt/d` worked as a path. 

Please do not comment with untested "solutions".

**Comment by benhillis** [comment]
Just to clarify the ask, you're asking if wslpath could understand Windows paths with the `\\?\` prefix? That should be easy, just want to clarify that's what you are asking for.
