### ISSUE TITLE
cannot find device bond0 after recent windows update

### ISSUE THREAD

**Issue by romarowski** [microsoft/WSL#9989]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

 1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.90.1

### Distro Version

Ubuntu 20.04

### Other Software

I am using bond0 to activate matlab licence inside WSL. This worked until today, I either attribute it to recent Windows update or that I installed an Ubuntu GUI app (Terminator) and all the config that came within.

### Repro Steps

ifconfig -a 

Used to show a bunch of networks including bond0, I honestly dont remember them.

### Expected Behavior

Used to show a bunch of networks including bond0, I honestly dont remember them.

### Actual Behavior

Only 

eth0:

lo:

**Comment by romarowski** [comment]
Could this be some change in the kernel? 
https://unix.stackexchange.com/questions/665520/multiple-virtual-network-interfaces-in-wsl2

**Comment by benhillis** [comment]
Yes this got change, were you using bond adapters for something?

**Comment by OneBlue** [comment]
Thanks for reporting @romarowski. We indeed removed that interface since it didn't seem to be useful to anyone. How exactly were you using this interface ? Is there a reason why eth0 doesn't work ?

**Comment by OneBlue** [comment]
Ok I see. In this case the easiest would probably to create that interface manually via something like:

```
ip link add name bond0 type bond mode active-backup
```

See [this post with more details](https://serverfault.com/questions/1064396/change-an-active-slave-of-linux-network-bonding-interface-without-ifenslave-comm)

You can add this to `boot.cmd` in `/etc/wsl.conf` if you want this to start automatically when WSL starts

**Comment by prot-eric** [comment]
Disagree that the workaround works.  I tried it, and bond0 disappears when wsl is rebooted.

**Comment by eric54321** [comment]
Disagree that the workaround from OneBlue solves problem. I tried it, and bond0 is missing upon wsl --shutdown and restart.

**Comment by eric54321** [comment]
Disagree that the workaround from OneBlue works.  I tried it, and the bond0 entry from ifconfig -a still disappears when restarting WSL2.
