### ISSUE TITLE
Can't Attach USB Devices to WSL

### ISSUE THREAD

**Issue by toml12953** [microsoft/WSL#9990]
### Windows Version

Microsoft Windows [Version 10.0.22624.1610]

### WSL Version

WSL version: 1.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

USBIP

### Repro Steps

On Linux, I run these commands with no errors:

sudo apt install linux-tools-generic hwdata
sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/*-generic/usbip 20

Then in a PowerShell terminal window, I run

usbipd wsl list

and I get a list of USB devices. The one I want is listed as BUSID 13-1.

Now I'm supposed to run

usbipd wsl attach --busid 13-1

but I get the error:

usbipd: error: The selected WSL distribution cannot be reached via the WSL virtual switch; try restarting the WSL distribution.

I try to restart WSL but get the same error.

### Expected Behavior

I should be able to run lsusb from Linux to get a list of the USB devices, including the one I attached.

### Actual Behavior

My USB device is not present.

**Comment by OneBlue** [comment]
Thanks for reporting this @toml12953.

This issue seems to come from usbpid, so the issue should be created [here](https://github.com/dorssel/usbipd-win).
