### ISSUE TITLE
Catastrophic failure: Wsl/Service/CreateInstance/E_UNEXPECTED

### ISSUE THREAD

**Issue by joelrb** [microsoft/WSL#9996]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

1.2023.1.0

### Distro Version

Kali Linux (2023.1 - rolling) 64-bit

### Repro Steps

1. Install kali-linux on a drive other than c:\ drive
2. Re-install kali-linux (wsl unregister current installation)
3. Reinstall kali-linux

### Expected Behavior

Successful kali-linux installation.

### Actual Behavior

Enter new UNIX username: jrb
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED

![kali error](https://user-images.githubusercontent.com/225284/233052851-443baff6-a78d-4242-9c26-6ee945359a83.png)

### Diagnostic Logs

[WslLogs-2023-04-19_18-36-18.zip](https://github.com/microsoft/WSL/files/11272155/WslLogs-2023-04-19_18-36-18.zip)

**Comment by benhillis** [comment]
Thanks for filing, unfortunately the logs you shared are not during the time when this error occured. Could you please re-collect logs, reproduce the issue, then end log collection?

Thanks.

**Comment by joelrb** [comment]
> 

How? I got the logs right after the error. I will try again.

**Comment by joelrb** [comment]
> 

Here's a new log and screenshot.
[WslLogs-2023-04-20_15-45-36.zip](https://github.com/microsoft/WSL/files/11283695/WslLogs-2023-04-20_15-45-36.zip)
![errorkali](https://user-images.githubusercontent.com/225284/233297344-3a254e1a-7dda-4a7d-91ad-b0427729634c.png)

**Comment by joelrb** [comment]
> This is very strange, I see in the log attempting to bind an AF_VSOCK socket is returning ENOSYS. Are you using a private kernel by chance? It might be helpful to take another trace of a full boot, so if you could do the following it would be very helpful. Thanks!
> 
> 1. wsl.exe --shutdown
> 2. start trace
> 3. repro issue
> 4. stop trace
> 
> Are you installing the kali from the store? I'm not able to reproduce this...

No. The Kali installer comes from the Microsoft Store. Also it worked before this error as I'm just reinstalling everything.

**Comment by joelrb** [comment]
I can't repro anymore. It works now. I have no idea what happened.

![Screenshot 2023-04-22 002213](https://user-images.githubusercontent.com/225284/233686552-dd112fb9-057f-4ce9-9455-833950d956ba.png)

**Comment by benhillis** [comment]
Glad it's resolved, if you hit this again please file a new issue. Thanks!
