### ISSUE TITLE
WSL fails to launch

### ISSUE THREAD

**Issue by goshathebusiness** [microsoft/WSL#9999]
### Windows Version

Microsoft Windows [Version 10.0.19044.2251]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 1
- [X] WSL 2

### Distro Version

Ubuntu 20.04

### Repro Steps

Run "wsl --install -d Ubuntu" in PowerShell

### Expected Behavior

Installing choosen distro and actual running

### Actual Behavior

Can't run WSL neither installed from Windows Store, neither PowerShell installed. Tried Ubuntu and Debian distros, same error everytime
![image](https://user-images.githubusercontent.com/104193037/233158006-109fea1f-15e1-4614-b800-d635edc972e3.png)
Error text in English is "This operation was returned because the waiting time expired error"

### Diagnostic Logs

[WslLogs-2023-04-19_20-29-41.zip](https://github.com/microsoft/WSL/files/11276215/WslLogs-2023-04-19_20-29-41.zip)

**Comment by OneBlue** [comment]
Thanks for reporting this @goshathebusiness. Looks like an issue that we fixed in [Store WSL](http://aka.ms/wslstorepage). Does installing Store WSL resolve the issue ?

**Comment by goshathebusiness** [comment]
@OneBlue already fixed by myself, thanks for attempt

**Comment by Totoro-wen** [comment]
@IlliaYalovoi，Hello，how do you fix this problem, I don't know what to do now.
.
